version: '3.8'

services:
  api:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=.localhost
      - ENVIRONTMENT=development
    volumes:
      - .:/app
    ports:
      - "8000:8000"